<?php

namespace AppBundle\Repository;

/**
 * OffersSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffersSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
