<?php

namespace AppBundle\Repository;

/**
 * UsersOffersBookmarkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersOffersBookmarkerRepository extends \Doctrine\ORM\EntityRepository
{
}
